
title = "@davelevy.cc"
baseURL = "http://davelevy.cc"
languageCode = "en-us"
theme = "ananke"


MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 4 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = "https://twitter.com/davelevy"
  instagram = ""
  # ello = "https://ello.co/davelevy"
  youtube = "https://www.youtube.com/channel/UCsM6HyTn4-6ZLJNRJE0eJIw"
  github = "https://github.com/dfl1955"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/davelevy/"
  mastodon = ""
  slack = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  # featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  featured_image = "/images/baloonsoveralton-w1440.jpg"
  recent_posts_number = 7



